Fix TS error about fromJSON
game/shared-helpers.ts:97:23 - error TS2345: Argument of type '{ _type: string; solid: boolean; }' is not assignable to parameter of type 'EntityLike'.
  Property 'fromJSON' is missing in type '{ _type: string; solid: boolean; }' but required in type 'Entity'.

97         entities.push({ ...entityData, _type: entityType })
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  game/entity.ts:9:3
    9   fromJSON(json: object): void {
        ~~~~~~~~
    'fromJSON' is declared here.